/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author zalaz
 */
public class VistaMateria extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaMateria
     */
    public VistaMateria() {

        initComponents();
        DesactivarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMateria = new javax.swing.JDesktopPane();
        jbCodigo = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jbAño = new javax.swing.JLabel();
        jbEstado = new javax.swing.JLabel();
        jTCodigo = new javax.swing.JTextField();
        jtAño = new javax.swing.JTextField();
        jTNombre = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jBNuevo = new javax.swing.JButton();
        jBExaminar = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ChekEstadoMateria = new javax.swing.JCheckBox();
        jBMostrarMateria = new javax.swing.JButton();
        jLapellido = new javax.swing.JLabel();
        jTApellido = new javax.swing.JTextField();

        setClosable(true);

        jbCodigo.setText("Codigo");

        jLNombre.setText("Nombre");

        jbAño.setText("año");

        jbEstado.setText("Estado");

        jTNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNombreActionPerformed(evt);
            }
        });

        jbBuscar.setText("Buscar");
        jbBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBNuevo.setText("Nuevo");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jBExaminar.setText("Examinar");

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("MATERIA");

        ChekEstadoMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChekEstadoMateriaActionPerformed(evt);
            }
        });

        jBMostrarMateria.setBackground(new java.awt.Color(0, 51, 51));
        jBMostrarMateria.setForeground(new java.awt.Color(0, 0, 0));
        jBMostrarMateria.setText("Mostar materia");
        jBMostrarMateria.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBMostrarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMostrarMateriaActionPerformed(evt);
            }
        });

        jLapellido.setText("Apellido");

        jTApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTApellidoActionPerformed(evt);
            }
        });

        jpMateria.setLayer(jbCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpMateria.setLayer(jLNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpMateria.setLayer(jbAño, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpMateria.setLayer(jbEstado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpMateria.setLayer(jTCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpMateria.setLayer(jtAño, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpMateria.setLayer(jTNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpMateria.setLayer(jbBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpMateria.setLayer(jBNuevo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpMateria.setLayer(jBExaminar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpMateria.setLayer(jBGuardar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpMateria.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpMateria.setLayer(ChekEstadoMateria, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpMateria.setLayer(jBMostrarMateria, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpMateria.setLayer(jLapellido, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpMateria.setLayer(jTApellido, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jpMateriaLayout = new javax.swing.GroupLayout(jpMateria);
        jpMateria.setLayout(jpMateriaLayout);
        jpMateriaLayout.setHorizontalGroup(
            jpMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMateriaLayout.createSequentialGroup()
                .addGroup(jpMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMateriaLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jpMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jpMateriaLayout.createSequentialGroup()
                                    .addComponent(jBNuevo)
                                    .addGap(38, 38, 38)
                                    .addComponent(jBGuardar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                    .addComponent(jBExaminar))
                                .addGroup(jpMateriaLayout.createSequentialGroup()
                                    .addGroup(jpMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jpMateriaLayout.createSequentialGroup()
                                            .addGroup(jpMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLNombre)
                                                .addComponent(jbCodigo)
                                                .addComponent(jbEstado))
                                            .addGap(38, 38, 38))
                                        .addGroup(jpMateriaLayout.createSequentialGroup()
                                            .addComponent(jbAño)
                                            .addGap(62, 62, 62)))
                                    .addGroup(jpMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jpMateriaLayout.createSequentialGroup()
                                            .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(52, 52, 52)
                                            .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                        .addComponent(jtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ChekEstadoMateria)
                                        .addComponent(jTApellido))))
                            .addComponent(jLapellido)))
                    .addGroup(jpMateriaLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jBMostrarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMateriaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        jpMateriaLayout.setVerticalGroup(
            jpMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMateriaLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jpMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCodigo)
                    .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jpMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombre)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLapellido)
                    .addComponent(jTApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jpMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAño))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbEstado)
                    .addComponent(ChekEstadoMateria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jBMostrarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBNuevo)
                    .addComponent(jBGuardar)
                    .addComponent(jBExaminar))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpMateria)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jpMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNombreActionPerformed

    private void ChekEstadoMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChekEstadoMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChekEstadoMateriaActionPerformed

    private void jBMostrarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMostrarMateriaActionPerformed
        jpMateria.repaint();
        VistaMostrarMateria a1 = new VistaMostrarMateria();
        a1.setVisible(true);
        jpMateria.add(a1);
        jpMateria.moveToFront(a1);
    }//GEN-LAST:event_jBMostrarMateriaActionPerformed

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        ActivarCampos();
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jTApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTApellidoActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        DesactivarCampos();
    }//GEN-LAST:event_jBGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ChekEstadoMateria;
    private javax.swing.JButton jBExaminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBMostrarMateria;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLapellido;
    private javax.swing.JTextField jTApellido;
    private javax.swing.JTextField jTCodigo;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JLabel jbAño;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JLabel jbCodigo;
    private javax.swing.JLabel jbEstado;
    private javax.swing.JDesktopPane jpMateria;
    private javax.swing.JTextField jtAño;
    // End of variables declaration//GEN-END:variables
    private void ActivarCampos() {
        jTCodigo.setEnabled(true);
        jTNombre.setEnabled(true);
        jTApellido.setEnabled(true);
        jtAño.setEnabled(true);
        ChekEstadoMateria.setEnabled(true);

    }

    private void DesactivarCampos() {
        jTCodigo.setEnabled(false);
        jTNombre.setEnabled(false);
        jTApellido.setEnabled(false);
        jtAño.setEnabled(false);
        ChekEstadoMateria.setEnabled(false);

    }

}
